appid: 123
appkey: 123
scope: snsapi_login
reflect_url: https://196.168.124.5/main
code_url: http://res.wx.qq.com/connect/zh_CN/htmledition/js/wxLogin.js
token_url: https://api.weixin.qq.com/sns/oauth2/access_token?grant_type=authorization_code
open_url: https://api.weixin.qq.com/sns/oauth2/refresh_token?grant_type=refresh_token
